### PR TITLE
Add support for RMP50XL

### PR DESCRIPTION
**Pull request by asisbot**

### CODE REVIEW

**Comment by piyushk** [comment]
@asisbot - You'll have to fix the pull request to pass the CI build.

**Comment by wjwwood** [comment]
lgtm, +1

**Comment by piyushk** [comment]
Same here, +1. While this PR looks extremely safe, I'll run some tests on one of our RMP 50s later this week before merging and re-releasing this package.

**Comment by paulbovbel** [comment]
Tested and working, could you please merge (and release for indigo)

**Comment by wjwwood** [comment]
Well, if it has been tested on hardware I'm ok with merging it, @piyushk will you have time to release it in the near future?

**Comment by piyushk** [comment]
Yes. I can release by the end of this week

**Comment by paulbovbel** [comment]
@piyushk, apologies, there's something not quite right with the parameters. Please hold off on the merge.

**Comment by piyushk** [comment]
@paulbovbel Please ping this thread when things look fine, and I will merge and release.

**Pull request closed without merging**
